FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src
COPY . .
RUN dotnet restore "src/Services/Webhooks/Webhooks.Api/Webhooks.Api.csproj"
RUN dotnet publish "src/Services/Webhooks/Webhooks.Api/Webhooks.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Webhooks.Api.dll"]
