using APITemplate.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace APITemplate.Infrastructure.Persistence.Configurations;

internal static class TenantAuditableEntityConfigurationExtensions
{
    public static void ConfigureTenantAuditable<TEntity>(this EntityTypeBuilder<TEntity> builder)
        where TEntity : class, IAuditableTenantEntity
    {
        builder.Property(e => e.TenantId)
            .IsRequired();

        builder.OwnsOne(e => e.Audit, audit =>
        {
            audit.Property(a => a.CreatedAtUtc)
                .HasColumnName("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasDefaultValueSql("now()");

            audit.Property(a => a.CreatedBy)
                .HasColumnName("CreatedBy")
                .IsRequired()
                .HasMaxLength(200)
                .HasDefaultValue(AuditDefaults.SystemActorId);

            audit.Property(a => a.UpdatedAtUtc)
                .HasColumnName("UpdatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasDefaultValueSql("now()");

            audit.Property(a => a.UpdatedBy)
                .HasColumnName("UpdatedBy")
                .IsRequired()
                .HasMaxLength(200)
                .HasDefaultValue(AuditDefaults.SystemActorId);
        });

        builder.Property(e => e.IsDeleted)
            .IsRequired()
            .HasDefaultValue(false);

        builder.Property(e => e.DeletedAtUtc)
            .HasColumnType("timestamp with time zone");

        builder.Property(e => e.DeletedBy)
            .HasMaxLength(200);

        // RowVersion is application-managed in AppDbContext (MarkUpdated),
        // not database-generated by a trigger/default.
        builder.Property(e => e.RowVersion)
            .IsConcurrencyToken()
            .ValueGeneratedNever()
            .HasColumnType("bytea");

        builder.HasIndex(e => e.TenantId);
        builder.HasIndex(e => new { e.TenantId, e.IsDeleted });

        builder.ToTable(t => t.HasCheckConstraint(
            $"CK_{builder.Metadata.GetTableName()}_SoftDeleteConsistency",
            "\"IsDeleted\" OR (\"DeletedAtUtc\" IS NULL AND \"DeletedBy\" IS NULL)"));
    }
}
